const projects=[
{title:'Techsoft Digi',category:'SEO',tag:'Technical SEO · Content',img:'techsoft-homepage',desc:'Website SEO work featuring technical configuration, sitemap and robots.txt documentation, and content optimization examples.',gallery:['techsoft-homepage','techsoft-sitemap','xml-sitemap','on-page-content']},
{title:'SEO Audits & Keyword Research',category:'SEO',tag:'Audit · Research',img:'dua-ruqyah-audit',desc:'Examples of website audits, keyword opportunity research and competitive on-page/off-page analysis.',gallery:['dua-ruqyah-audit','keyword-research','technical-audit','competitor-research']},
{title:'E-commerce Technical SEO',category:'SEO',tag:'WordPress · Technical SEO',img:'ecommerce-technical',desc:'Technical SEO configuration examples for an e-commerce environment.',gallery:['ecommerce-technical','technical-audit']},
{title:'A3 Sports',category:'Social Media',tag:'Social management · Planning',img:'a3-facebook',desc:'Social media optimization, cross-platform content planning, Facebook page setup and Messenger automation examples.',gallery:['a3-facebook','a3-instagram','a3-content-calendar','a3-automation']},
{title:'Churi Ghor',category:'Social Media',tag:'Social creative · Product design',img:'churi-01',desc:'Branded social media product creatives featuring handmade bangles.',gallery:['churi-01','churi-02','churi-03','churi-04']},
{title:'4Flow',category:'Social Media',tag:'B2B content · Creative planning',img:'4flow-01',desc:'B2B supply-chain and logistics social graphics on optimization, sustainability and technology.',gallery:['4flow-01','4flow-02','4flow-03','4flow-04','4flow-05']},
{title:'Global Piks',category:'Social Media',tag:'E-commerce · Content planning',img:'globalpiks-post-01',desc:'Cross-platform product content planning and social media post examples for consumer products.',gallery:['globalpiks-post-01','globalpiks-post-02','globalpiks-post-03','globalpiks-reel','globalpiks-calendar']},
{title:'Global Sync',category:'Social Media',tag:'Education · Social content',img:'globalsync-03',desc:'Social media content planning and education-focused campaign creatives.',gallery:['globalsync-03','globalsync-01','globalsync-02']},
{title:'Meta Pixel Setup',category:'Tracking',tag:'Meta Pixel · Event setup',img:'meta-pixel',desc:'A documented Meta Pixel events setup example.',gallery:['meta-pixel']}
];
const img=(name)=>`assets/${name}.webp`;
const grid=document.getElementById('projectGrid');const dialog=document.getElementById('projectDialog');const gallery=document.getElementById('dialogGallery');
function showProjects(filter='All'){grid.replaceChildren();projects.forEach((p,i)=>{if(filter!=='All'&&p.category!==filter)return;const b=document.createElement('button');b.className='project';b.type='button';b.setAttribute('aria-label',`View ${p.title} project`);b.innerHTML=`<div class="project-img"><img loading="lazy" alt="${p.title} project work sample" src="${img(p.img)}"></div><div class="project-content"><span class="project-meta">${p.tag}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="project-bottom"><span>VIEW CASE STUDY</span><b>↗</b></div></div>`;b.addEventListener('click',()=>openProject(i));grid.append(b)})}
function openProject(i){const p=projects[i];document.getElementById('dialogTitle').textContent=p.title;document.getElementById('dialogDesc').textContent=p.desc;gallery.replaceChildren();p.gallery.forEach((name,j)=>{const a=document.createElement('a');a.href=img(name);a.target='_blank';a.rel='noopener noreferrer';a.title='Open full-size project screenshot';const image=document.createElement('img');image.src=img(name);image.alt=`${p.title} supporting screenshot ${j+1}`;image.loading='lazy';a.append(image);gallery.append(a)});dialog.showModal()}
document.getElementById('closeDialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true');showProjects(b.dataset.filter)}));
const skills=[['Search Engine Optimization',90],['Social Media Management & Marketing',95],['Social Media Ads Campaign',95],['Meta Pixel',90],['AI Tools Proficiency',95],['WordPress Customization',85],['Project Management',95]];const skillBox=document.getElementById('skillBars');skills.forEach(([name,value])=>{const item=document.createElement('div');item.className='skill';item.innerHTML=`<div class="skill-head"><span>${name}</span><strong>${value}%</strong></div><div class="track"><div class="fill" style="width:${value}%"></div></div>`;skillBox.append(item)});
document.getElementById('year').textContent=new Date().getFullYear();const menuBtn=document.getElementById('menuBtn');const mobile=document.getElementById('mobileNav');menuBtn.addEventListener('click',()=>{const open=menuBtn.getAttribute('aria-expanded')!=='true';menuBtn.setAttribute('aria-expanded',String(open));mobile.hidden=!open});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.hidden=true;menuBtn.setAttribute('aria-expanded','false')}));showProjects();
